### PR TITLE
Changed docker.skip to docker.skip.build to avoid creating docker image

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by dhirajsb** [comment]
ok to test

**Comment by jimmidyson** [comment]
Surprised that `docker.skip` doesn't skip the build? @rhuss?

BTW there's no PR build stuff for this repo afaik, so just merge when you're happy & then have to run the seed job on CI infra.

**Comment by dhirajsb** [comment]
@jimmidyson yeah, that was a surprise to me as well, merged and will kick off the ci job

**Comment by dhirajsb** [comment]
@jimmidyson think it's skipping more than the image build atm, but docker.build is supposed to skip everything, which is still trying to pull product base image from redhat registry which fails in product branch PR

**Pull request merged**
